---
title: "RNA-seq clustering"
html_notebook: default
github_document: default

---


```{r init-workspace, message=FALSE, warning=FALSE}
if (! require(devtools)) {
  install.packages("devtools")
  library(devtools)
}

LoadPackages <- function(pkg.name, pkg.install = pkg.name, repo = "CRAN") {
  if (! require(pkg.name)) {
    if (repo == "CRAN") {
    install.packages(pkg.install)
    } else if (repo == "github") {
      devtools::install_github(pkg.install)
    }
  }
  library(pkg.name)
}

req.packages <- rbind(c("igraph", "igraph/rigraph", "github"),
                      c("Rphenograph", "Rphenograph", "github"))
apply(req.packages, 1, function(x) LoadPackages(x[1], x[2], x[3]))


```

```{r load data}


```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).
